### ISSUE TITLE
Problem with input 

### ISSUE THREAD

**Issue by elpic** [mlaass/jomohojs#1]
I don't know how to know if a user type something ?

The example doesn't work

```
    if(game.state ===  'play'){
        if(jo.input.key(jo.input.UP)){
        }
        if(jo.input.key(jo.input.DOWN)){

        }
    }
```

**Comment by mlaass** [comment]
yeah have chnaged the Api a little in the last weeks, but havent updated the example.
If you want to gather input you can use the following
if(jo.input.k('UP')) // check if key up is pressed

if(jo.input.once('UP')) // check if key UP is pressed for the first time, used for toggling stuff
